### ISSUE TITLE
手机端提交内容到服务器图片会丢失

### ISSUE THREAD

**Issue by lgd5555** [wangfupeng1988/wangEditor-mobile#2]
插入一张图片
![qq 20160104193457](https://cloud.githubusercontent.com/assets/13177391/12088962/dc6f9e24-b31a-11e5-859f-e91cadf69960.jpg)

数据库的内容如下
< p >李礼< /p >< p >< br >< /p >

如果添加两张图片，那么后面添加的图片就会没有,这是为何？

**Comment by lgd5555** [comment]
我用谷歌模拟上传时没有问题的
![qq 20160104194340](https://cloud.githubusercontent.com/assets/13177391/12089036/8a5ee490-b31b-11e5-8774-e5942a4a7808.png)

**Comment by wangfupeng1988** [comment]
我根据你说的情况做了一下调整，在每次上传图片完成之后，都保存一下源代码，这样应该不会出现问题了。

去下载最新代码试试吧  https://github.com/wangfupeng1988/wangEditor-mobile/releases

如果还有问题，再即使跟我反馈。

**Comment by lgd5555** [comment]
nice，问题解决了，棒棒哒！！
